# This is the pre-commit configuration file
# It defines hooks to be executed during commit actions

repos:
  # Official pre-commit hooks repository
repos:
  - repo: file:///path/to/pre-commit/pre-commit-hooks  # Use the absolute path to your local clone
    rev: main  # Or any specific branch or commit you want to use
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: yamllint
      - id: check-added-large-files
      - id: shellcheck
      - id: detect-secrets
      - id: flake8

      - id: flake8
        args: ['--max-line-length=100']


