repos:
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v5.0.4  # Specify the version of flake8
    hooks:
      - id: flake8
        name: flake8
        description: Lint Python code with flake8
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-trailing-whitespace
    rev: v1.0.0  # Specify the version for trailing-whitespace
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: Automatically remove trailing whitespace
        files: .*
