# .pre-commit-config.yaml

# This is the root level configuration for the pre-commit hooks

# Define the list of repositories and hooks to run
repos:
  - repo: https://github.com/pre-commit/mirrors-bandit
    rev: v1.7.4  # Use the specific version of the Bandit hook
    hooks:
      - id: bandit
        args: ['--quiet']

  - repo: https://github.com/GitLeaks/GitLeaks
    rev: v8.8.3  # Use the specific version of Gitleaks
    hooks:
      - id: gitleaks
        args: ['--verbose']

  - repo: https://github.com/pre-commit/mirrors-talisman
    rev: v1.18.0
    hooks:
      - id: talisman

