version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hassen12/foyer_backend:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hassen
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer  # This sets the context path for Spring Boot
    depends_on:
      - db
    networks:
      - foyer-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hassen
      MYSQL_DATABASE: db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - foyer-network

  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /c/Users/msi/Desktop/tp-foyer/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  my-grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - /c/Users/msi/Desktop/tp-foyer/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password


networks:
  foyer-network:
    driver: bridge

volumes:
  db_data:
  grafana_data:

