version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mnifmohamed547/foyer_backend:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/foyer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - db
    networks:
      - foyer-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: foyer
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - foyer-network

networks:
  foyer-network:
    driver: bridge

volumes:
  db_data:
