version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xhalakox/foyer_backend:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/foyer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - db
    networks:
      - foyer-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: foyer
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - foyer-network

  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"  # Change the host port to 9091
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistent data volume for Prometheus
    networks:
      - foyer-network

  my-grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"  # Change the host port to 3001
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - grafana_data:/var/lib/grafana  # Persistent data volume for Grafana
    networks:
      - foyer-network

networks:
  foyer-network:
    driver: bridge

volumes:
  db_data:           # MySQL data storage
  prometheus_data:    # Prometheus data storage
  grafana_data:       # Grafana data storage
