services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=timesheet_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app-timesheet:
    depends_on:
      - mysqldb
    image: ademmelki/tp-foyer:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring": {
          "datasource": {
            "url": "jdbc:mysql://mysqldb:3306/timesheet_db?createDatabaseIfNotExist=true",
            "username": "root",
            "password": "rootpassword",
            "driver-class-name": "com.mysql.cj.jdbc.Driver"
          },
          "jpa": {
            "hibernate": {
              "ddl-auto": "update"
            },
            "properties": {
              "hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
            }
          }
        }
      }'
    stdin_open: true
    tty: true
    entrypoint: /bin/bash -c "echo 'Container app-timesheet Started' && java -jar /path/to/your/app.jar"  # Custom log and start app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db:
