global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'tp_foyer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8089']  # Use service name 'app' and internal port 8089
        labels:
          application: 'Foyer Application'

  - job_name: 'jenkins'  # Renamed job for clarity
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['my-prometheus:9090']  # Targeting Prometheus container itself
      - targets: ['app:8080']  # Assuming 'app' has a Prometheus endpoint on 8080
